Update dependencies, source/url, and add sha256
AnacondaRecipes/ncurses-feedstock pull request #5
Opened 2021-10-28 12:21 UTC by skupr-anaconda

Update to 6.3

Actions:
1. Update source/url. The old one hasn't the release v6.3
2. Add sha256 and remove md5
3. Disable patches `ncurses-5.9-gcc-5.patch`, `fix.patch`, and `clang.patch`
4. Update build.sh: add `PKG_CONFIG_LIBDIR `and change `"${PREFIX}"` to` "${BUILD_PREFIX}"`

2021-10-28 12:21 UTC, skupr-anaconda commented
Errors:

```
checking for ggrep... no
checking for grep... grep
checking for egrep... grep -E
Configuring NCURSES 6.3 ABI 6 (Thu Oct 28 08:37:08 UTC 2021)
checking for package version... 6.3
checking for package patch date... 20211021
checking build system type... x86_64-conda-linux-gnu
checking host system type... x86_64-conda-linux-gnu
checking target system type... x86_64-conda-linux-gnu
Configuring for linux-gnu
checking for fgrep... grep -F
checking for prefix... $PREFIX
checking for x86_64-conda-linux-gnu-gcc... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
checking for C compiler default output... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for executable suffix... 
checking for object suffix... o
checking whether we are using the GNU C compiler... yes
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc accepts -g... yes
checking version of $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc... 86
checking if this is really Intel C compiler... no
checking if this is really Clang C compiler... no
checking for $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc option to accept ANSI C... none needed
checking $CFLAGS variable... ok
checking $CC variable... ok
checking how to run the C preprocessor... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc needs -traditional... no
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc understands -c and -o together... yes
checking for ldconfig... /usr/sbin/ldconfig
checking if you want to ensure bool is consistent with C++... yes
checking for x86_64-conda-linux-gnu-g++... $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++
checking whether we are using the GNU C++ compiler... yes
checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ accepts -g... yes
checking if $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ works... yes
checking version of $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++... 86
checking if you want to build C++ binding and demo... yes
checking if you want to build with Ada... no
checking if you want to install terminal database... yes
checking if you want to install manpages... no
checking if you want to build programs such as tic... yes
checking if you want to build test-programs... yes
checking if you wish to install curses.h... yes
checking for mawk... no
checking for gawk... gawk
checking for a BSD compatible install... /usr/bin/install -c
checking for lint... no
checking for cppcheck... no
checking for splint... no
checking whether ln -s works... yes
checking if ln -s -f options work... yes
checking for long file names... yes
checking if you want to use pkg-config... yes
checking for x86_64-conda-linux-gnu-pkg-config... no
checking for pkg-config... $BUILD_PREFIX/bin/pkg-config
checking for $BUILD_PREFIX/bin/pkg-config library directory... checking for first directory... none
checking if we should install .pc files for $BUILD_PREFIX/bin/pkg-config... yes
configure: error: expected a pathname, not ""
```

2021-10-28 13:00 UTC, katietz requested changes
Additionally, is there no change necessary to builds.sh?

2021-10-28 13:00 UTC, katietz commented on recipe/meta.yaml
> +    #- ncurses-5.9-gcc-5.patch
In such cases remove the line completely .. we don't need to keep this patch, if it is no longer necessary.  Also the patch-file you can be removed from recipe

2021-10-28 13:25 UTC, chenghlee requested changes

2021-10-28 13:25 UTC, chenghlee commented on recipe/meta.yaml
> +  url: https://github.com/mirror/ncurses/archive/refs/tags/v{{ version }}.tar.gz
The canonical source repository is https://invisible-mirror.net/archives/ncurses/. We should use that instead of a GitHub mirror.

2021-10-28 13:25 UTC, chenghlee commented on recipe/meta.yaml
> +    - {{ compiler('cxx') }}
The dependency on the C++ compiler was removed about a year ago. We should investigate to determine what's changed.

2021-10-28 13:25 UTC, chenghlee commented on recipe/meta.yaml
>      - fix.patch
We should check if this patch is still necessary. If it hasn't already been integrated into the upstream code base after 10 years, we should be asking why.

2021-10-28 13:50 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - {{ compiler('cxx') }}
Yeah. I'm misreading these lines in logs:
```
configure: WARNING: Ignore g++, since it cannot compile hello-world.
configure: WARNING: You don't have any C++ compiler, too bad
```
TOO BAD :)

2021-10-28 13:51 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - fix.patch
Yeah, without patches conda-build can build. I removed them

2021-10-28 13:51 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  url: https://github.com/mirror/ncurses/archive/refs/tags/v{{ version }}.tar.gz
Done

2021-10-28 14:02 UTC, skupr-anaconda commented
I found here https://fossies.org/linux/ncurses/configure that error
```
checking for pkg-config... $BUILD_PREFIX/bin/pkg-config
checking for $BUILD_PREFIX/bin/pkg-config library directory... checking for first directory... none
checking if we should install .pc files for $BUILD_PREFIX/bin/pkg-config... yes
configure: error: expected a pathname, not ""
```
can be related to `pkg_config` 
```
 4100 case ".$PKG_CONFIG" in
 4101 (.\$\(*\)*|.\'*\'*)
 4102     ;;
 4103 (..|./*|.\\*)
 4104     ;;
 4105 (.[a-zA-Z]:[\\/]*) # OS/2 EMX
 4106     ;;
 4107 (.\$\{*prefix\}*|.\$\{*dir\}*)
 4108     eval PKG_CONFIG="$PKG_CONFIG"
 4109     case ".$PKG_CONFIG" in
 4110     (.NONE/*)
 4111         PKG_CONFIG=`echo "$PKG_CONFIG" | sed -e s%NONE%$cf_path_syntax%`
 4112         ;;
 4113     esac
 4114     ;;
 4115 (.no|.NONE/*)
 4116     PKG_CONFIG=`echo "$PKG_CONFIG" | sed -e s%NONE%$cf_path_syntax%`
 4117     ;;
 4118 (*)
 4119     { { echo "$as_me:4119: error: expected a pathname, not \"$PKG_CONFIG\"" >&5
 4120 echo "$as_me: error: expected a pathname, not \"$PKG_CONFIG\"" >&2;}
 4121    { (exit 1); exit 1; }; }
 4122     ;;
 4123 esac
```
or 

```
 4280 
 4281 case ".$PKG_CONFIG_LIBDIR" in
 4282 (.\$\(*\)*|.\'*\'*)
 4283     ;;
 4284 (..|./*|.\\*)
 4285     ;;
 4286 (.[a-zA-Z]:[\\/]*) # OS/2 EMX
 4287     ;;
 4288 (.\$\{*prefix\}*|.\$\{*dir\}*)
 4289     eval PKG_CONFIG_LIBDIR="$PKG_CONFIG_LIBDIR"
 4290     case ".$PKG_CONFIG_LIBDIR" in
 4291     (.NONE/*)
 4292         PKG_CONFIG_LIBDIR=`echo "$PKG_CONFIG_LIBDIR" | sed -e s%NONE%$cf_path_syntax%`
 4293         ;;
 4294     esac
 4295     ;;
 4296 (.no|.NONE/*)
 4297     PKG_CONFIG_LIBDIR=`echo "$PKG_CONFIG_LIBDIR" | sed -e s%NONE%$cf_path_syntax%`
 4298     ;;
 4299 (*)
 4300     { { echo "$as_me:4300: error: expected a pathname, not \"$PKG_CONFIG_LIBDIR\"" >&5
 4301 echo "$as_me: error: expected a pathname, not \"$PKG_CONFIG_LIBDIR\"" >&2;}
 4302    { (exit 1); exit 1; }; }
 4303     ;;
 4304 esac
```

2021-10-29 06:59 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    #- ncurses-5.9-gcc-5.patch
Done

2021-10-29 07:00 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    #- ncurses-5.9-gcc-5.patch
I removed all patches

2021-10-29 07:32 UTC, katietz requested changes

2021-10-29 07:32 UTC, katietz commented on recipe/meta.yaml
> -    - clang.patch
Why removing the clang.patch, and the fix.patch? This looks wrong

2021-10-29 07:34 UTC, skupr-anaconda commented
@katietz Thanks for your help. Now I fixed issues and the `ncurses 6.3` build succeeded on osx64, linux64, linux-ppc64le, but not on `aarch64` and `arm64`.
On aarch64 the issue with:
`checking for $BUILD_PREFIX/bin/aarch64-conda-linux-gnu-pkg-config library directory... checking for first directory... none
`
and 
```
( cd ncurses && make DESTDIR="" RPATH_LIST="$PREFIX/lib" install )
make[1]: Entering directory '$SRC_DIR/ncurses'
linking $PREFIX/lib/libtinfow.so.6.3
/opt/conda/conda-bld/ncurses_1635490972214/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/10.2.0/../../../../aarch64-conda-linux-gnu/bin/ld: total time in link: 0.026903
/opt/conda/conda-bld/ncurses_1635490972214/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/10.2.0/../../../../aarch64-conda-linux-gnu/bin/ld: total time in link: 0.035572

/usr/bin/install: cannot run strip: No such file or directory
```

I can't realise why it failed on `arm64`

2021-10-29 07:54 UTC, skupr-anaconda commented
I returned fix.patch and clang.patch

2021-10-29 07:54 UTC, skupr-anaconda commented on recipe/meta.yaml
> -    - clang.patch
Returned them

2021-10-29 09:08 UTC, katietz commented
The log tells you what it is "/usr/bin/install: cannot run strip: No such file or directory" ... which means that strip tool isn't installed into build environment.

2021-11-01 15:44 UTC, closed without merging